### PR TITLE
Add 'etime' to the 'imp' object

### PR DESCRIPTION
**Pull request by simontrasler**
This field is submitted separately from #14 since it can serve the "ad refresh" use case as well.

### CODE REVIEW

**Comment by robhazan** [comment]
This was already reviewed in the previous PR, so I'm just going to merge it. Also seems like a reasonable change to me, for whatever that's worth :-)

**Comment by patmmccann** [comment]
Exposure time feels a lot like size to me, it could be a vector and a response could bid different amounts on each value.

**Comment by robhazan** [comment]
@patmmccann - does that imply that you would like some change to this spec? Or is this just commentary?

**Comment by simontrasler** [comment]
This (lot size) is not a model that has come up in discussions. The use case here (for both DOOH and on the web) is that the player prescribes a single fixed amount of time for playing the ad.

**Pull request merged**
